### ISSUE TITLE
Error deserialising output of `cargo test --doc`

### ISSUE THREAD

**Issue by xd009642** [oli-obk/cargo_metadata#102]
I got the deserialisation message `Err(Error("expected value", line: 3, column: 1))` when running `parse_messages` on the piped output of: `cargo +nightly test --message-format json --manifest-path tarpaulin/tests/data/doc_coverage/Cargo.toml --doc`

Below is the json (but prettified):

```
{
   "reason":"compiler-artifact",
   "package_id":"doc_coverage 0.1.0 (path+file:///home/xd009642/code/rust/tarpaulin/tests/data/doc_coverage)",
   "target":{
      "kind":[
         "lib"
      ],
      "crate_types":[
         "lib"
      ],
      "name":"doc_coverage",
      "src_path":"/home/xd009642/code/rust/tarpaulin/tests/data/doc_coverage/src/lib.rs",
      "edition":"2018",
      "doctest":true
   },
   "profile":{
      "opt_level":"0",
      "debuginfo":2,
      "debug_assertions":true,
      "overflow_checks":true,
      "test":false
   },
   "features":[

   ],
   "filenames":[
      "/home/xd009642/code/rust/tarpaulin/tests/data/doc_coverage/target/debug/deps/libdoc_coverage-c0b9eafea90c1625.rlib",
      "/home/xd009642/code/rust/tarpaulin/tests/data/doc_coverage/target/debug/deps/libdoc_coverage-c0b9eafea90c1625.rmeta"
   ],
   "executable":null,
   "fresh":false
}
```

**Comment by ehuss** [comment]
I think `parse_messages` is misleading for how to parse JSON output.  At a minimum, it would be best to only parse lines that start with `{`, like this:

```rust
    let mut reader = BufReader::new(command.stdout.unwrap());
    for line in reader.lines() {
        let line = line.unwrap();
        if line.starts_with('{') {
            let message: Message = serde_json::from_str(&line).unwrap();
            println!("{:#?}", message);
        }
    }
```

Additionally, you may want to scan for lines to stop looking for JSON output. For example, you don't want to continue parsing with `cargo run` when it starts executing the process. One tool I wrote has "stop lines" that will abort processing, like the regex `^\s*Running `.  I filed https://github.com/rust-lang/cargo/issues/7978 for improving that.

In this case, `test --doc` is emitting test results to stdout.

**Comment by xd009642** [comment]
Ah I see! It would be helpful in this case if `--doc` also allowed the `--no-run` option because that's likely how my other usage is working fine

**Comment by oli-obk** [comment]
We now have a more robust message parsing scheme
