### ISSUE TITLE
Test default values of exposed library types

### ISSUE THREAD

**Issue by kolloch** [oli-obk/cargo_metadata#103]
Currently, it is really hard to write tests using the types exposed in this library. This is because code outside of the library cannot construct them -- as far as I can see.

The types follow roughly this pattern, `Metadata` is just an example:

```rust
#[derive(Clone, Serialize, Deserialize, Debug)]
/// Starting point for metadata returned by `cargo metadata`
pub struct Metadata {
    /// A list of all crates referenced by this crate (and the crate itself)
    pub packages: Vec<Package>,
    /// ... some more fields ...
    #[doc(hidden)]
    #[serde(skip)]
    __do_not_match_exhaustively: (),
}
```

This keeps users of this library from getting compile errors when fields are added. It also keeps them from constructing these types.

It would be nice to have a way to construct these values with default values and then override only the values that are needed to be overridden.

A current workaround would be to deserialize the wanted values from JSON but that seems rather silly.

**Comment by oli-obk** [comment]
Hmm.. is checking each field individually too cumbersome? My first instinct was to say "load from json" which you mentioned...
We could add a cargo feature that makes all types exhaustively matcheable just for tests

**Comment by kolloch** [comment]
Maybe, I haven't phrased it clear enough but how do I test a method that takes Metadata as an argument?

```rust
fn my_func(meta: &Metadata) -> Something {
/// ...
}
```

I don't think that a cargo feature to match all types exhaustively would be nice since it would mean that 

* I still have to list all the fields, even though the ones I don't care about.
* The code would break if you add fields.

Maybe load from JSON is good enough, though, it is not that bothersome. Properly, I would construct my own types, though, that have a subset of fields.

Having a "test-values" feature, including test constructors for all values would be nicer.

**Comment by oli-obk** [comment]
We could derive `Default` for all types. Then you can create a value and set the fields that are relevant for you.

Just adding test constructors won't really help you because their arguments will quickly diverge when we add more fields

**Comment by kolloch** [comment]
One of the problems is that there are not necessarily good values for all fields, e.g. names (an empty string is kind of an illegal value). What I meant with test constructors was actually just something that would produce test data...

**Comment by oli-obk** [comment]
I usually produce test data by running this crate on itself or some other crate. If you want to produce random data that is not illegal, I feel like you'd end up putting in a really large amount of work. If you want "random" input, you can scrape crates.io and just start picking random crates I guess.

**Comment by kolloch** [comment]
I do have integration tests. I'd also like unit tests.

**Comment by oli-obk** [comment]
I understand that, but I don't know how you would generate test data. Are you looking for something like quickcheck's test data generator?

Basically I'm unsure how to resolve your issue, because I only see two reasonable ways:

1. a cargo feature that makes the types exhaustive
2. deserializing from json

We can't have a `fn new` like constructor taking arguments, because if we add new fields to the struct, the `new` constructor can't be changed (that would be a breaking change), but it still needs to fill that field. So in that situation the `new` constructor would have to generate a random value, and it may not actually be useful to generate such a value.

My personal opinion is that since the only use case is testing, deserializing from json is the way to go. You can make this more structured by using the `serde_json::json!` macro.

**Comment by kolloch** [comment]
I would just fill the object with mock data. No need for arguments. Unit tests should override data that they need to override or that is relevant to their tests.

This is what many test stubs that I used do. 

Create a user? Fine, I'll give it a full name because that is required but you don't have to specify anything.

But don't worry, feel free to close. I can easily solve this for me but it genuinely felt like a shared concern.
