### ISSUE TITLE
impl Error for cargo_metadata::Error?

### ISSUE THREAD

**Issue by bjgill** [oli-obk/cargo_metadata#11]
It would make using `cargo_metadata::Error` substantially easier.

Would it make sense, perhaps, to switch over to [`error-chain`](https://crates.io/crates/error-chain)?

**Comment by oli-obk** [comment]
Definitely! I don't have much experience with `error-chain`, but I'll happily accept PRs ;)

**Comment by bjgill** [comment]
Fixed in #15
