### ISSUE TITLE
Expose whether bin/lib target has tests enabled

### ISSUE THREAD

**Issue by RalfJung** [oli-obk/cargo_metadata#114]
There currently seems to be no way to figure out if a bin/lib target has tests enabled. Would be great if that information was made available -- I think that is required to solve https://github.com/rust-lang/miri/issues/700.

**Comment by ehuss** [comment]
The information isn't exposed from Cargo. The additional fields need to be added to [`SerializedTarget`](https://github.com/rust-lang/cargo/blob/cb06cb2696df2567ce06d1a39b1b40612a29f853/src/cargo/core/manifest.rs#L253-L266).

**Comment by RalfJung** [comment]
Oh I see...

Btw, the comment "Serialized as a list of strings for historical reasons" for the `kind` field, does this mean we can rely on that list to always contain exactly one element? It is not clear from the comment what type would be used if it wasn't for historical reasons.

**Comment by ehuss** [comment]
> rely on that list to always contain exactly one element?

No. The documentation that explains the fields is [here](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html).

I'm only guessing, but I think it would have been preferred for libraries to have a value of `"lib"`, instead of the array of crate-types.

**Comment by RalfJung** [comment]
Oh wow, I think Miri is getting that wrong then... we just check for "lib".

The "etc" doesn't exactly help when one wants to be sure to cover all lib crates.^^

**Comment by oli-obk** [comment]
Uh... so is there any action that I can do about this in `cargo_metadata` or is it essentially resolved?

**Comment by RalfJung** [comment]
It's not resolved but blocked on cargo exposing `test = true/false`.

**Comment by oli-obk** [comment]
The cargo PR has been merged

**Comment by RalfJung** [comment]
Awesome. :D
Does this crate also need updating or is that picked up automatically somehow?

**Comment by oli-obk** [comment]
no, we need to wait for this information to make it to a release and then add the appropriate field
