### ISSUE TITLE
make cargo_metadata::Source an enum?

### ISSUE THREAD

**Issue by matthiaskrgr** [oli-obk/cargo_metadata#116]
I wonder if it makes sense to make [`cargo_metadata::Source`](https://docs.rs/cargo_metadata/0.10.0/cargo_metadata/struct.Source.html) an enum that represents whether the crate is a registry, path or git dependency.

That way users wouldn't have to parse the string manually.

**Comment by oli-obk** [comment]
I wasn't sure what kind of further cases could come up. We could do this and add `#[nonexhaustive]` to the enum I guess.

**Comment by sunshowers** [comment]
You could consider using [guppy](https://crates.io/crates/guppy) which is built on top of `cargo_metadata` and has a [structured representation of the package source](https://docs.rs/guppy/0.5.0/guppy/graph/enum.PackageSource.html), along with many other features.

(disclosure: I'm its primary author and maintainer.)

**Comment by oli-obk** [comment]
Don't we end up with a cycle if we depend on guppy and guppy depends on us? We could move the relevant guppy datastructures here and then make guppy use/reexport them?

**Comment by sunshowers** [comment]
Ah yeah to be clear my suggestion was to @matthiaskrgr. But I'd be fine with moving the guppy representation into cargo_metadata if you think it's good, though I'm not sure I can get to it in the short term.

**Comment by sunshowers** [comment]
Though I suspect the guppy representation might be a bit more structure than cargo_metadata is looking for, since guppy also tries to figure out workspace vs non-workspace packages which feels out of the ambit of cargo_metadata.

**Comment by oli-obk** [comment]
Ok, yea, in that case, this falls into the usual case of `cargo_metadata` being too low level for the requested use case. I'll close this issue. Maybe we should mention guppy in the README and docs so people know there's a higher level alternative
