### ISSUE TITLE
Windows 10 OS Error 5 Access Denied

### ISSUE THREAD

**Issue by pmkroeker** [oli-obk/cargo_metadata#117]
I have been struggling to get wasm-pack to run. I keep getting and `OS Error 5: Access Denied` message. [wasm-pack issue](https://github.com/rustwasm/wasm-pack/issues/803)

After doing some digging I found that the error seems to be originating from [a call to cargo_metadata](https://github.com/rustwasm/wasm-pack/blob/9f9634ca9ffa9147c044f947a31808f02715aa44/src/manifest/mod.rs#L416)

What might cause this to throw this error? My rust is version `rustc 1.44.0` with the windows toolchain `stable-x86_64-pc-windows-msvc`. I have tried changing permissions on files and folders that are relevant to the project.

**Comment by oli-obk** [comment]
you can try editing wasm-pack to use `cargo_command` in order to dump the command line that we use here and then run this command line yourself on your shell. Maybe that will give you more insights on what is wrong.

**Comment by pmkroeker** [comment]
Thanks. Ya I'll do some more digging today.

**Comment by pmkroeker** [comment]
After some more digging, I realized that wasm-pack uses version 0.8.0 of this package. I bumped my local clone to the latest version (0.10.0) and everything worked.
