### ISSUE TITLE
Expose Dependency kind and version requirement?

### ISSUE THREAD

**Issue by bjgill** [oli-obk/cargo_metadata#12]
I'm hoping to use `cargo_metadata` for [`cargo-edit`](https://github.com/killercup/cargo-edit) to get a full list of all the direct dependencies of crates in a workspace.

For this to be useful, however, it would be nice if `Dependency` were to expose the kind and version.

**Comment by oli-obk** [comment]
Just open a PR to make fields public that you need, I simply kept all fields private that I didn't need. If a struct's fields all become public, add a private field that is defaulted, so we can keep extending the struct in the future without major version bumps.

**Comment by bjgill** [comment]
It would be nice to be able to have the dependency version as a `VersionReq` (rather than a `String`). However, I think https://github.com/steveklabnik/semver/issues/119 currently blocks this.

**Comment by oli-obk** [comment]
You can always use `deserialize_with` to work around that.

**Comment by bjgill** [comment]
I'm trying to fix it at source with https://github.com/steveklabnik/semver/pull/122

**Comment by bjgill** [comment]
OK - semver can now deserialize `VersionReq`, so this will be trivial to fix once a new version of semver is released.

**Comment by oli-obk** [comment]
Once we get this, I'll publish a new major version.

**Comment by oli-obk** [comment]
:tada: Do you have any other breaking changes you wanted to get into the next major release?

**Comment by bjgill** [comment]
I don't think so. #19 is the only issue outstanding, and it doesn't seem particularly important.

**Comment by bjgill** [comment]
@oli-obk - when were you planning to publish the new version?

**Comment by oli-obk** [comment]
ups. on it. sorry!

**Comment by oli-obk** [comment]
Published 0.3

**Comment by bjgill** [comment]
Thank you :tada:
