### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by UebelAndre** [oli-obk/cargo_metadata#134]
Would it be possible to get a new release. I'm interested in the updated `semver` dependency.

**Comment by ehuss** [comment]
There should already be a new release: https://crates.io/crates/cargo-clone-crate/0.1.4

**Comment by UebelAndre** [comment]
@ehuss This is for https://crates.io/crates/cargo_metadata right? Did I post this in the correct place? 😅

**Comment by ehuss** [comment]
Oh, sorry! 😆   I misread and was confused.

**Comment by UebelAndre** [comment]
All good 😄 

But I do really appreciate the `cargo-clone-crate` release as well! 🙏

**Comment by oli-obk** [comment]
I was just waiting for https://github.com/oli-obk/cargo_metadata/pull/133 will publish in a bit

**Comment by oli-obk** [comment]
published as 0.12

**Comment by UebelAndre** [comment]
Thank you so much!
