### ISSUE TITLE
Add `impl Default for Target`

### ISSUE THREAD

**Issue by jyn514** [oli-obk/cargo_metadata#136]
I want to write some unit tests for a function taking `Target`. But since there's no way to construct a Target myself, I can't test it, other than by writing the string manually and deserializing + unwrapping. It would be nice to be able to use `Target { kind: ..., crate_types: ..., ..Target::default() }`.

**Comment by jyn514** [comment]
Actually even that doesn't work:
```rust
        assert!(!has_docs(&Target {
            kind: vec!["example".into()],
            crate_types: vec!["cdylib".into()],
            ..default()
        }));
```
```
error[E0451]: field `__do_not_match_exhaustively` of struct `cargo_metadata::Target` is private
   --> src/main.rs:241:15
    |
241 |             ..default()
    |               ^^^^^^^^^ field `__do_not_match_exhaustively` is private
```
I guess I can use strings for all the tests and parse them each time? That seems pretty repetitive.

**Comment by jyn514** [comment]
I ended up going with this:
```rust
    fn target(crate_types: &str, kind: &str) -> Target {
        serde_json::from_str(&format!(r#"{{
            "crate_types": ["{}"],
            "kind": ["{}"],
            "name": "simple",
            "src_path": "",
            "edition": "2018",
            "doctest": false,
            "test": false
        }}"#, crate_types, kind)).unwrap()
    }
```
It works for me ™️ but it would be nice to have a sanctioned way to do this.

**Comment by oli-obk** [comment]
hehe interesting... does this work with `#[nonexhaustive]` instead of that non exhaustiveness field hack?

**Comment by jyn514** [comment]
Good idea - yes, non_exhaustive fixes it: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4dde1eb44bda22c7ff23c5ca486a3da8. That + `Default` would be really nice :)

**Comment by oli-obk** [comment]
Ok, cool, I'm fine with bumping MSRV to the minimal needed for ´#[nonexhaustive]` and then finally get rid of all the hacks related to that

**Comment by jyn514** [comment]
Ahhh it turns out that only worked because it was in the same crate :cry: 

```
---- src/lib.rs - Target (line 382) stdout ----
error[E0639]: cannot create non-exhaustive struct using struct expression
 --> src/lib.rs:384:17
  |
5 |   let my_target = Target {
  |  _________________^
6 | |     kind: vec!["example".into()],
7 | |     crate_types: vec!["cdylib".into()],
8 | |     ..Target::default()
9 | | };
  | |_^

error: aborting due to previous error
```

I don't know how to fix this ... I wish non_exhaustive were less strict :(

**Comment by oli-obk** [comment]
we can create a builder, then you only need to invoke the builder methods for the fields you actually want to set

**Comment by jyn514** [comment]
Hmm, that will work but it's a lot of boilerplate - it means you need to write a builder for each struct you want. It seems weird to have a builder for `Target` but nothing else.

**Comment by oli-obk** [comment]
Maybe someone wrote  crate that autogenerates builders?

**Comment by oli-obk** [comment]
> Maybe someone wrote crate that autogenerates builders?

The Rust community does not disappoint: https://crates.io/crates/derive_builder

**Comment by oli-obk** [comment]
that worked like a charm. https://github.com/oli-obk/cargo_metadata/blob/0abf09ac37f05131970d8d472dd1c38c821d3924/src/lib.rs#L388-L428

Next step: port all other non_exhaustive structs
