### ISSUE TITLE
`homepage` and `documentation` fields are missing for `Package`

### ISSUE THREAD

**Issue by jyn514** [oli-obk/cargo_metadata#140]
This is blocking https://github.com/rust-lang/docs.rs/pull/1143.

**Comment by jyn514** [comment]
These were only added in 1.49, so I guess they should be an `Option`, but it seems reasonable to have them in the metadata at all even if cargo isn't always emitting them.

**Comment by jyn514** [comment]
I'm interested in working on this.

**Comment by oli-obk** [comment]
Yea, we should definitely add them. And as an `Option` as you described. We have several other optional fields that are defaulted to `None` on older `cargo` versions. If you add a test it will get automatically tested on various Rust versions on CI.

I can publish a new version any time in the next 3 or 4 hours today, after that it'll have to wait until tomorrow. Feel free to ping me on zulip/discord the moment any action from my side is required......


....oh that was fast
