### ISSUE TITLE
Why stringly typed data?

### ISSUE THREAD

**Issue by qrilka** [oli-obk/cargo_metadata#151]
It's more of a question and probably I don't see enough details but why Target.kind has a type `Vec<String>` and doesn't use a proper `enum` for kinds? Could a kind contain an arbitrary string?

**Comment by oli-obk** [comment]
sometimes because I didn't put the effort in to actually figure out what variants it has, sometimes because for backwards compat, it needs to accept any string. Basically we need to check what the actual rules in cargo are and then we can make the implementation more strict.

**Comment by oli-obk** [comment]
I'm going to do a major version bump again soon, so if you have any changes like this that you want to get in, now is a good time. I'm closing this issue now since I'm not going to track this explicitly.

**Comment by qrilka** [comment]
@oli-obk I once again touched a some lines in `cargo-geiger` related to this package. Do you have any upcoming changes which are not in `master` which you plan for this upcoming major version bump? I was just wandering if that could help `cargo-geiger` in some way...

**Comment by oli-obk** [comment]
I'm still fixing something on master, but in general, that is the plan for the next release

**Comment by msrd0** [comment]
Is this still something you'd like to see changed? It looks like cargo's targets have one single kind which is an enum: https://docs.rs/cargo/0.64.0/src/cargo/core/manifest.rs.html#205
