### ISSUE TITLE
Consider making `derive-builder` optional

### ISSUE THREAD

**Issue by lnicola** [oli-obk/cargo_metadata#154]
Crates that only consume the metadata might want to avoid additional proc macro dependencies because of the build time implications.

Would you be willing to make the builders optional? Of course, that would also imply avoiding using them in the `cargo-metadata` proper.

**Comment by oli-obk** [comment]
oh, good idea. we should make it a cargo feature.

**Comment by oli-obk** [comment]
>  Of course, that would also imply avoiding using them in the cargo-metadata proper.

ah, indeed, that is too bad :/

I'll revert that part to the handwritten version

**Comment by oli-obk** [comment]
Done, yanked the 0.13.0 (already happened yesterday) and published 0.13.1
