### ISSUE TITLE
Where are the examples mentioned in the readme?

### ISSUE THREAD

**Issue by danielzfranklin** [oli-obk/cargo_metadata#161]
Hi, first off I want to thank you for this library. It's been tremendously helpful in writing [a library for building various things](https://docs.rs/seacan/0.0.1/seacan/) with cargo.

In the readme you mention

```
Documentation - contains examples of use with std::env::args, docopt, clap, and structopt.
```

I don't see anything like that in the docs, and I'm unsure how argument parsing relates to what this crate has to offer. Did I miss something?

**Comment by oli-obk** [comment]
those were removed a while back... I guess we just need to adjust the readme, too

**Comment by danielzfranklin** [comment]
Good to know. I made a tiny PR.

**Comment by oli-obk** [comment]
you need to open the PR against this repo, you opeend it against your own ;)
