### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by illicitonion** [oli-obk/cargo_metadata#164]
Hi! Is there any chance of a release on crates.io which includes https://github.com/oli-obk/cargo_metadata/pull/163 ? It'd be handy for updating a crate I maintain which depends on this.

Thanks,

**Comment by oli-obk** [comment]
Sorry, I'm still on leave until 5th of July. I haven't been at a PC that has cargo on it for almost 3 months. I'll do the release in the week of the 5th

**Comment by illicitonion** [comment]
Fantastic, thanks - I hope you're having good leave!

**Comment by Ericson2314** [comment]
Looking forward to this too!

While you were at it, I think some tags for versions 0.13.x are missing.

**Comment by oli-obk** [comment]
Released 0.14 and added tags

**Comment by Ericson2314** [comment]
Thanks!!
