### ISSUE TITLE
Limit dependency graph to direct dependencies

### ISSUE THREAD

**Issue by good-praxis** [oli-obk/cargo_metadata#178]
Hey there! I've been running into some issues trying to contribute to cargo-license. I talked about the issue we're facing there here: https://github.com/onur/cargo-license/issues/47#issuecomment-1117670873

But to the TL;DR is, when `MetadataCommand`'s method `no_deps()` gets called the `resolve` field on the final `metadata` will stay empty. While the root dependencies are still accessible as `Dependency` structs in the root package, these are lacking the metadata expected of them (authors, license, etc)

Now a possible workaround I started working on was manually getting the Ids of the root and it's direct depenencies, either from `packages[0]` or from `resolve.root`, however that just doesn't work out nicely since the entire code expects to traverse a dependency graph.

Is it at all feasible to add code that would filter the `resolve` for only the root dependencies, with a similar flag as `no_deps`? Or should I be looking for another solution?

**Comment by oli-obk** [comment]
I'm not sure. This crate is just a thin wrapper around calling `cargo metadata` manually. Do you see the info you need in the output of `cargo metadata --no-deps`?

**Comment by good-praxis** [comment]
No, not at all. It seems like it'll only consider the root package and not it's direct dependencies then. Which links up to the documentation.

So long story short supporting this usecase is an issue for cargo instead of this package, then?
