### ISSUE TITLE
Re-exporting `semver`?

### ISSUE THREAD

**Issue by 8573** [oli-obk/cargo_metadata#179]
Like [`camino`](https://lib.rs/crates/camino), [`semver`](https://lib.rs/crates/semver) is in `cargo_metadata`'s API, but, [unlike with `camino`](https://github.com/oli-obk/cargo_metadata/issues/171), `cargo_metadata` does not re-export the version of `semver` that it uses.  I suggest that `cargo_metadata` also re-export `semver` so that users can be sure of using the same version `cargo_metadata` uses.

I could file a PR, but
```diff
 pub use camino;
-pub use semver::{Version, VersionReq};
+pub use semver::{self, Version, VersionReq};
```
is such a simple change that I figure handling a PR would be more work for you. :-)

<small>(In case it matters, I dedicate the above patch under CC0-1.0.)</small>

**Comment by UebelAndre** [comment]
https://github.com/oli-obk/cargo_metadata/commit/1b4aea8dee94652c4f27a5e2f4e0dc07d3da6e55 seems to be a followup change.
