### ISSUE TITLE
Consider using thiserror for the Error impl

### ISSUE THREAD

**Issue by morr0ne** [oli-obk/cargo_metadata#188]
Currently the Error is manually implemented but I think it might be worth using [thiserror](https://github.com/dtolnay/thiserror) to greatly simplify the code. I'd normally be against adding needless dependency but since the crates make use serde_derive we wouldn't actually be pulling in any new dependency expect the derive macro. Testing on my poor 4 core intel cpu didn't had even a milliseconds to build time since the heave dependencies (quote, syn, proc_macro2) have already been compiled.

**Comment by oli-obk** [comment]
Huh does serde depend on thiserror nowadays?

**Comment by oli-obk** [comment]
I think I added a few convenience deps before and people noticed, need to do some archeology to see what the reasons were

**Comment by morr0ne** [comment]
> Huh does serde depend on thiserror nowadays?

I think I worded it wrong, I apologize for that. What I meant is that the only dependencies pulled in by thiserror are quote, proc_macro2 and syn. However this dependencies are already being pulled in by serde_derive meaning thiserror isn't detrimental in any way to the library user since it doesn't add any new dependency beside itself, which if look at the source is a relatively simple proc_macro.

**Comment by oli-obk** [comment]
I agree ^^ I just remember that others didn't. I'll dig through old issues and PRs to see if I can find the rationale so we can make a decision here knowing we looked at all arguments

**Comment by morr0ne** [comment]
Fair enough, this crate is quite important in the rust ecosystem. Making hasty choises isn't a good idea.

**Comment by morr0ne** [comment]
@oli-obk maybe you were refering to #146? If that's the case then I think it's should be fine. Thiserror is actually a very simple crate, it just implement the Standard library Error/Display traits nothing less nothing more. If you run cargo expand you can see that the generated code is basically the same as the old manual implementation. Eyre on the other hand pulls in a bunch of stuff since is meant to be used more in binary crates rather than libraries.

**Comment by oli-obk** [comment]
@jyn514 opinions? The compilation time hit is probably negligible and it does simplify the crate.

**Comment by morr0ne** [comment]
Within a margin of error I couldn't detect any difference in compile at all. It makes sense since the heavy dependencies were already in the tree. Ofc if other people can confirm my claims it'd be great.

**Comment by jyn514** [comment]
I think thiserror would be ok to use, yeah - my main concern in https://github.com/oli-obk/cargo_metadata/pull/146 was that the error library doesn't show up in the API, which thiserror achieves.

**Comment by oli-obk** [comment]
Cool, merged the PR then
