### ISSUE TITLE
Which fields in `cargo metadata` output have ordering guarantees?

### ISSUE THREAD

**Issue by bjgill** [oli-obk/cargo_metadata#19]
Currently, all the lists produced by `cargo metadata` are converted into `Vec`s. However, this is probably not correct for unordered collections.

`dependencies` is the main example of this unordered behaviour, and should probably be a `HashSet<Dependency>`. I haven't checked to see if this is true for any other fields.

**Comment by oli-obk** [comment]
I'm not against it. I don't really care either way though. A `Vec` of unordered things is fine by me, especially since you don't need any constraints like `Hash` or `PartialEq`

**Comment by matklad** [comment]
No fields in `cargo metadata` have any significant ordering. That said, I think a `Vec` is the perfect type to represent an unordered collection of things in Rust: unlike Java, we don't have `Collection`.

**Comment by oli-obk** [comment]
Since I was minorly in favour of `Vec` and @matklad also thinks that, I'm closing this issue
