### ISSUE TITLE
Remove camino/Make it optional?

### ISSUE THREAD

**Issue by morr0ne** [oli-obk/cargo_metadata#193]
Currently camino's Utf8PathBuf is used in the metadata object instead of the standard library PathBuf. However it seems rather strict to only allow utf8 paths since some more esoteric operating systems, such as windows, sometimes don't return valid utf8 data but valid paths nonetheless. I feel like utf8 validation should fall on the library consumer side and not enforced by this library. Maybe it could be made optional and enabled via a cargo feature?

**Comment by jplatte** [comment]
Does cargo itself support non-utf8 paths? I was running under the assumption that it doesn't, and in that case I think using camino here is exactly the right thing to do.

**Comment by morr0ne** [comment]
But what is the reason to use utf8 paths? I don't see why utf8 paths should be used in this context. They don't seem to provide any benefits and I had needless errors return because of it. Utf8 validation can still be performed after, but throwing away the whole metadata because some path wasn't utf8 doesn't make any sense.

**Comment by jplatte** [comment]
One thing that I've found very convenient is that `Utf8Path` has a `Display` impl.

But aldo thinking more about it, almost all the camino paths used in this crate are deserialized from JSON, right? In that case, only utf-8 paths are possible anyways, as JSON is utf-8 and doesn't provide an escaped representation of non-utf8 bytes. serde_json will emit an error when you try to serialize a non-utf8 `Path`(`Buf`).

**Comment by morr0ne** [comment]
> serde_json will emit an error when you try to serialize a non-utf8 `Path`(`Buf`).
If that's the case isn't camino even more redunant?

**Comment by oli-obk** [comment]
There was previous discussion in https://github.com/oli-obk/cargo_metadata/pull/152

I don't know the best way forward. Some days I wish for implicit conversion from wrapper types to their wrapped types ^^ (not really, but still)



> If that's the case isn't camino even more redunant?

not quite. It's already possible to rely on the fact that the paths are utf8, what the use of camino types does here is to encode this information in the type system. I like this a lot, but I also see that nonstandard types are not always ideal. But if no one adopts new helper crates and types, they can't really become standard-by-convention. So... 🤷 good arguments for all sides, but the main forker (rust-analyzer) will fork either way, so there isn't really any loss here.

**Comment by morr0ne** [comment]
My main argument is that for anyone, like me, that doesn't need nor care about utf8 paths but really just wants a normal std path it doesn't actually had anything of value. I mostly end up converting it to a std path anyway adding a useless extra layer. On the other hand anyone requiring utf8 paths will already be using `camino` anyway so they can just perform validation on their own.

> However it seems rather strict to only allow utf8 paths since some more esoteric operating systems, such as windows, sometimes don't return valid utf8 data but valid paths nonetheless.

As I kinda alluded to before, camino has caused crashes for me on some (albeit rare) occasions, which do not happen when using the normal std version. Learning that `cargo`, `serde` and the Json spec all require utf8 makes that kinda perplexing so it might be worth investigating that further.

**Comment by morr0ne** [comment]
After reading the discussion in #152 I really agree with all of @matklad (forgive the ping) points execpt for the fact that I don't really have the luxury to fork as I need my crates to come from `crates.io` in many cases.

**Comment by oli-obk** [comment]
> As I kinda alluded to before, camino has caused crashes for me on some (albeit rare) occasions, which do not happen when using the normal std version.

irrespective of whether we remove camino, we should probably add tests for those crashes if you can find them again. Adding a windows builder to CI for this should not be an issue

**Comment by sunshowers** [comment]
Hi there, maintainer of camino here -- I was pointed to this issue.

> but throwing away the whole metadata because some path wasn't utf8 doesn't make any sense.

So:
* JSON is a Unicode document by definition and can't represent non-UTF-8 paths.
* Serde's [`PathBuf` deserializer](https://docs.rs/serde/1.0.152/src/serde/de/impls.rs.html#1666-1704) doesn't work with non-UTF-8 paths.
* In addition, cargo, or any other cross-platform system which has files that contain the names of other files, **cannot** even theoretically support non-UTF-8 paths due to what's sometimes called [the makefile problem](https://www.mercurial-scm.org/wiki/EncodingStrategy#The_.22makefile_problem.22).

I personally use and rely on UTF-8 paths heavily, and I think most projects should use UTF-8 paths.

> I'd love add some test cases but I honestly don't know how to reproduce those crashes.

I would definitely be interested in seeing backtraces for those crashes! Camino is in pretty wide use and there haven't been any bugs related to this being filed. Camino just uses std's UTF-8 validation so I'm not sure how useful fuzzing it would be.

**Comment by morr0ne** [comment]
Unfortunately I can't seem to remember how or when I encountered this issue, considering it's been 7 months It's not really surprising. I am 100% sure the issue was caused by the utf-8 validation since switching to regular Path fixed all the crashes. At this point I wonder if I encountered some sort of deeper problem within the std utf-8 validation. The crash happened under a windows 10 vm (using qemu on linux) so perhaps that might the cause of the issues?

Adding some kind of fuzzing to camino still feels like a sensible thing to do. Maybe even the std parsing logic should be fuzzed but I'd assume that's already the case.

**Comment by sunshowers** [comment]
That's really strange for sure. My uninformed guess is that std's UTF-8 validation might have tried to use a processor instruction that wasn't available in your qemu environment.

**Comment by sunshowers** [comment]
Though, hmm, in that case I'm not sure how you managed to deserialize a `PathBuf`, given that `PathBuf`'s deserializer also relies on the same UTF-8 validation (`Utf8PathBuf`'s deserializer depends on this property, it's just a `#[serde(transparent)]` wrapper over `PathBuf`'s.)

**Comment by morr0ne** [comment]
I'll try investigating some more. I do wonder if I just encountered bug in serde instead of the actual utf-8 validation. Sadly I wasn't using any fancy panic handler like eyre at the the time, making the source of the error much harder to locate. If I find something more I'll make sure to open an issue on the camino repo.

Beside the crashing I still fill like cargo_metadata should just use regular paths. It does pull in an extra dependency and I never found any benefit in having UTF-8 paths in this crate since I always end up passing them to other std functions which don't care about the utf-8 validation anyway. Beside if anyone needs that kind of validation they can still pull camino themselves. I am not sure what the general consensus is but I do find it unnecessary.

**Comment by slonopotamus** [comment]
> One thing that I've found very convenient is that `Utf8Path` has a `Display` impl.

This is not an argument, both `std::path::PathBuf` and `std::path::Path` have `display()` function that returns a `Display` impl.

**Comment by sunshowers** [comment]
While that is true, a lot of programs have bugs lurking in them around non-UTF8 paths when they use the Display implementation, typically because they've hit some version of the makefile problem. Rejecting them at the boundaries of your program in a principled way is strictly better than that.

**Comment by slonopotamus** [comment]
> Rejecting them at the boundaries of your program in a principled way is strictly better than that.

I would agree with you, but I'm not sure cargo_metadata should decide whether its consumers are unable to fix their non-unicode path bugs and should just give up. If utf-8-ness of paths was enforced by language/OS/libc, this would be perfectly fine.

**Comment by sunshowers** [comment]
In this case it's enforced by cargo as well as serde_json.

**Comment by oli-obk** [comment]
I think we've seen all discussions that I can think of and the only argument that is still open is whether we should be using nonstandard types in our public API. At this point I don't see us coming to a conclusion, so I'll stick with my original point that "if no one uses new stuff then no new stuff can ever catch on". The small ergonomic issue of having to call `to_path_buf` or similar in situations where you need to pass a camino type to a library using a stdlib type seems minor to me, considering we also do the same for other fields that are just backed by a string in json.

Thanks everyone for the nice and constructive discussion.

**Comment by morr0ne** [comment]
Forgive me for commenting after you closed the issue but I wanted to add one final remark.

I actually have to eat back my words and agree that using camino is the correct choice. serde_json already performs UTF-8 validation regardless of cargo_metadata using standards paths or camino. We are basically getting UTF-8 paths for free. Not using camino is probably worse since you need to add an extra validation step. Converting from camino's paths to normal ones is pretty much trivial and we get a nice display implementation that is panic safe and more ergonomic to use.

My original issue was born from a fundamental misunderstanding of both camino and serde_json handling of paths.

Looking back at it, I feel kinda dumb for opening this issue but I am happy I learned something out of it.
