### ISSUE TITLE
Lack of LICENSE file

### ISSUE THREAD

**Issue by BenjaminGill-Metaswitch** [oli-obk/cargo_metadata#20]
It seems to be the norm to provide a LICENSE file. This repo doesn't seem to have one (though Cargo.toml specifies MIT).

Maybe copy https://github.com/rust-lang/rust/blob/master/LICENSE-MIT?

**Comment by oli-obk** [comment]
Done

**Comment by BenjaminGill-Metaswitch** [comment]
Excellent. Thank you!
