### ISSUE TITLE
`workspace.default-members` key is missing from output

### ISSUE THREAD

**Issue by ZhaoXiangXML** [oli-obk/cargo_metadata#215]
According to the [doc of `cargo build`](https://doc.rust-lang.org/cargo/commands/cargo-build.html):

> The default members of a workspace can be set explicitly with the `workspace.default-members` key in the root manifest.

However there's no such field in the output of `cargo metadata`.

Is there a workaround to this other than parsing the toml file?

**Comment by oli-obk** [comment]
> Is there a workaround to this other than parsing the toml file?

creating a PR to this crate that adds it? 😆, unfortunately there's no workaround, no, sorry.

**Comment by ZhaoXiangXML** [comment]
Well, thanks anyway

**Comment by ZhaoXiangXML** [comment]
Maybe I can simply ignore it for now, I don't really need this field

**Comment by sunshowers** [comment]
See https://github.com/rust-lang/cargo/issues/8033 — this has shipped in Rust 1.71.
