### ISSUE TITLE
readme can also be a boolean

### ISSUE THREAD

**Issue by heaths** [oli-obk/cargo_metadata#234]
According to [documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field), you can specify `readme = false` to disable readme lookups. I had opened https://github.com/rustwasm/wasm-pack/pull/1216 to fix this, but they took a dependency on this crate that also declares it as only an optional string.

https://github.com/oli-obk/cargo_metadata/blob/010cd78751e51dc48d0ca08ca0f4be3ac054a689/src/lib.rs#L324

**Comment by oli-obk** [comment]
Closing as per the discussion on #235
