### ISSUE TITLE
Why is `PackageId` opaque but `SourceId` not?

### ISSUE THREAD

**Issue by weihanglo** [oli-obk/cargo_metadata#237]
In https://github.com/rust-lang/cargo/pull/12313, the Cargo team is discussing `PackageId` and `SourceId` should be seen as being opaque. We found that for `PackageId` in `cargo_metadata` crate [it is mentioned as opaque](https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.PackageId.html), but for `SourceId` [it's not](https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.Source.html). I wonder if there was a reason this crate didn't say the inner representations of `SourceId` is also opaque, or you've spotted some valid use cases. Thank you :)

**Comment by oli-obk** [comment]
That's just an oversight. We should document it as opaque, too
