### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by sunshowers** [oli-obk/cargo_metadata#245]
Hi!

Wondering if it would be possible to release a new version with support for the new debuginfo added in [#241](https://github.com/oli-obk/cargo_metadata/pull/241). A nextest user ran into https://github.com/nextest-rs/nextest/issues/910 which is caused by that. Thanks!

**Comment by oli-obk** [comment]
I won't get to this until next week, but if someone does the major version bump as a PR I can make GHA do a publish

**Comment by oli-obk** [comment]
A new version has been published
