### ISSUE TITLE
the default value of Edition field is 2015, it can't tell the difference edition set with 2015 and edition not set.

### ISSUE THREAD

**Issue by linyihai** [oli-obk/cargo_metadata#250]
How to know that rust edition not set in Cargo.toml? I want to know whethe edition is set or not in the Cargo.toml. 
In this situation, I found that the Edition offered by the cargo_metadata crate set the default value 2015, so I had no idea to know rust edition is not set in cargo.toml, because it will be set the default value 2015 when serde_json crate parse the toml file.

the relative code is below:

https://github.com/oli-obk/cargo_metadata/blob/main/src/lib.rs
```
    /// Beware that individual targets may specify their own edition in
    /// [`Target::edition`].
    #[serde(default)]
    pub edition: Edition,

    fn default() -> Self {
        Self::E2015
    }
}

```

Forgive my poor english expression since i am not native english speaker.  My need is to know whethe edition is set or not in the Cargo.toml. Maybe the cargo_metadata can offer a way to tell the edition not set in the Cargo.toml, like this

```
    fn had_set() -> bool {
        TODO!()
    }
```

**Comment by weihanglo** [comment]
`cargo_metadata` is a consumer of the output of [`cargo metadata`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) command. `cargo metadata` sets `"edition": "2015"` when the field is missing in `Cargo.toml`.

I don't think this crate `cargo_metadata` can detect the situation you describe.

>  My need is to know whethe edition is set or not in the Cargo.toml

If possible, please share why you need to know it is not set, and maybe we can come up with a better alternative.

**Comment by linyihai** [comment]
> `cargo_metadata` is a consumer of the output of [`cargo metadata`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) command. `cargo metadata` sets `"edition": "2015"` when the field is missing in `Cargo.toml`.
> 
> I don't think this crate `cargo_metadata` can detect the situation you describe.
> 
> > My need is to know whethe edition is set or not in the Cargo.toml
> 
> If possible, please share why you need to know it is not set, and maybe we can come up with a better alternative.

**Comment by linyihai** [comment]
@weihanglo thanks for you reply. The background is that i make a custom lint to check whethe the rust edition is set or not. the detail is:
- [add no rust edition lint](https://github.com/rust-lang/rust-clippy/commit/ff9cad156d897f312e3f3e926ba6868d04d70e77)

`cargo_metadata` is also used by `rust-clippy` repository. in my pr as above, i get the rust edition offered by `cargo_metadata`.

```
use super::NO_RUST_EDITION;
use cargo_metadata::Metadata;
use clippy_utils::diagnostics::span_lint;
use rustc_lint::LateContext;
use rustc_span::source_map::DUMMY_SP;

pub(super) fn check(cx: &LateContext<'_>, metadata: &Metadata) {
    for package in &metadata.packages {
        // indeed, rust editon allow omited and the default value is 2015. to avoid read all cargol.toml
        // file and make it simple, if the rust edition newer than the default(2015), then it can be
        // treated had rust edition configed
        if package.edition < cargo_metadata::Edition::E2018 {
            let message = format!("package `{}` is missing `edition` metadata", package.name);
            span_lint(cx, NO_RUST_EDITION, DUMMY_SP, &message);
        }
    }
}
```

without the `cargo_metadata`, i have no way to get the rust edition unless i write my cargo.toml parser function.

**Comment by weihanglo** [comment]
My personal stance would be like: the lint should either be implemented in Cargo or reuse the TOML manifest parser in Cargo. Either way, I agree `cargo_metadata` at this point has no way to provide what you're looking for.

See this zulip discussion for more: https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Cargo.20Lints/near/389439777

**Comment by linyihai** [comment]
> cargo metadata sets "edition": "2015" when the field is missing in Cargo.toml.

That's true. So the left possible way to detect Edition` unsetting is read the `Cargo.toml` though.
