### ISSUE TITLE
`cargo test -- --format json` support?

### ISSUE THREAD

**Issue by bend-n** [oli-obk/cargo_metadata#251]
Wondering if you'd be willing to expand it, to support `cargo test`, specifically `cargo test --message-format json -- -Zunstable-options --report-time --show-output --format json` output.

Ive implemented the test part already, in my [cargo-kewl](https://github.com/bend-n/cargo-kewl/blob/master/src/cargo.rs#L53-L80) project, so id be willing to make a PR for it.

**Comment by oli-obk** [comment]
Oh yea, we should totally add it. We'll need a big message about the json format being unstable tho.

**Comment by bend-n** [comment]
Should I provide a `TestCommand` too? One that spawns a thread and holds a `std::sync::mpsc` channel?
