### ISSUE TITLE
How to extract `rust-version` field with Cargo 1.56?

### ISSUE THREAD

**Issue by joshlf** [oli-obk/cargo_metadata#253]
The [`Package::rust_version`](https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.Package.html#structfield.rust_version) field's docs state:

> The [`rust-version` field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) as specified in the `Cargo.toml`. The minimum supported Rust version of this package.
>
> This is always `None` if running with a version of Cargo older than 1.58.

Is there a work-around that will allow extracting this field when running with Cargo 1.56 (the first version which parses and interprets this field)?

**Comment by oli-obk** [comment]
Oops. I didn't check this correctly. If you open a PR that fixes this and does a patch bump, I can merge and release it

**Comment by jplatte** [comment]
I don't think there's something to be fixed here?

The only workaround I can think of is to parse `$CARGO_MANIFEST_DIR/Cargo.toml`.

**Comment by joshlf** [comment]
> Oops. I didn't check this correctly. If you open a PR that fixes this and does a patch bump, I can merge and release it

So it looks like the documentation is actually correct, and `cargo metadata` only learned to parse `rust_version` in 1.58. I'm just wondering if there's a workaround or a way to fix the behavior. Running locally from the `cargo_metadata` repo:

```text
$ function get_rust_version_with_toolchain {
    cargo +"$1" metadata --format-version 1 | jq -r ".packages[] | select(.name == \"cargo_metadata\").rust_version"
}
$ get_rust_version_with_toolchain 1.56
null
$ get_rust_version_with_toolchain 1.57
null
$ get_rust_version_with_toolchain 1.58
1.56.0
```

**Comment by oli-obk** [comment]
> I don't think there's something to be fixed here?
> 
> The only workaround I can think of is to parse `$CARGO_MANIFEST_DIR/Cargo.toml`.

Ah in that case this is the only solution. We're not going to add this to this crate, as the simpler fix is to bump your cargo version
