### ISSUE TITLE
Don't panic from WorkspaceDefaultMembers?

### ISSUE THREAD

**Issue by sourcefrog** [oli-obk/cargo_metadata#254]
Hi, https://docs.rs/cargo_metadata/0.18.1/cargo_metadata/struct.WorkspaceDefaultMembers.html documents that it will panic on cargo <1.70, and it does.

For cargo-mutants, I'd like to use this but also support older versions of cargo, so it would be really nice if this was a runtime error rather than a panic. Or at least, if there was a documented version field that I could check before looking at it. Possibly I am missing some subtlety about why that's not feasible.

Thanks for a really helpful crate.

**Comment by jplatte** [comment]
As a workaround, you can use [`std::panic::catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) to resume operation in case of a panic (unless you're compiling without unwinding).

**Comment by oli-obk** [comment]
You can use the https://crates.io/crates/rustc_version crate to check whether your rust is new enough for this field

**Comment by sourcefrog** [comment]
Also, just to confirm, this hinges on the version of `cargo` that's being invoked as `cargo metadata`, not on the version used to build the program, right?

**Comment by oli-obk** [comment]
yes

**Comment by clechasseur** [comment]
I ran into this issue also. Would it be acceptable to add a method to the `WorkspaceDefaultMembers` type to be able to check if it's available or not? If so, I can volunteer to work on a PR for this.

**Comment by Shnatsel** [comment]
I'm also interested in this for `cargo auditable` and I'm happy to contribute a PR.

**Comment by foresterre** [comment]
From [cargo-msrv](https://github.com/foresterre/cargo-msrv/) there would also be interest. Happy to help if necessary.

**Comment by oli-obk** [comment]
I guess. User needs trump whatever reasons I have

**Comment by foresterre** [comment]
> I guess. User needs trump whatever reasons I have

I opened a PR in #282. However, if you feel that this is not in scope for this project, then that's of course also fine.
