### ISSUE TITLE
Metadata fails in offline mode

### ISSUE THREAD

**Issue by infogulch** [oli-obk/cargo_metadata#257]
If there are any git deps then cargo metadata requires access to the network to download it before running.

I'm using it to get the names of packages in the current workspace to clean them after a ci run to minimize cache usage.

```console
cargo clean --offline -p `cargo metadata --offline --format-version 1 | jq -r '[.workspace_members[]|split(" ")|.[0]]|join(" ")'`
```

But it seems silly to download a bunch of packages just to list the workspace members.

Thoughts?

**Comment by ehuss** [comment]
I think you can use the `--no-deps` option to avoid network access.

**Comment by infogulch** [comment]
Ah I didn't notice that option, that helps. But now it looks like `cargo clean --offline` has the same problem, which is just ridiculous 😞

**Comment by oli-obk** [comment]
This is not a cargo_metadata issue, as we just shell out to `cargo metadata`. You'll need to open an issue in the `rust-lang/cargo` repo

**Comment by infogulch** [comment]
Thank you!
