### ISSUE TITLE
Lib package names from `cargo` differ (dash vs. underscore)

### ISSUE THREAD

**Issue by adpaco-aws** [oli-obk/cargo_metadata#259]
The change in https://github.com/rust-lang/cargo/pull/12783 causes `cargo` to return lib package names which are different to the names obtained through `cargo metadata`. More specifically, the `cargo` name will use underscores (`_`) instead of dashes (`-`), otherwise they are the same.

We first noticed this discrepancy during a Rust toolchain upgrade in https://github.com/model-checking/kani/pull/3102, where we worked around this issue by introducing a weaker comparison between the targets. `cargo metadata` was specifically mentioned in [this comment](https://github.com/rust-lang/cargo/pull/12783) from https://github.com/rust-lang/cargo/pull/12783 as an area that would be affected.

What's the long-term plan to avoid the discrepancy? Does `cargo metadata` need to do the same replacement?

**Comment by oli-obk** [comment]
We're only processing information that cargo provides to us. So if cargo sends us dashes, we'll report dashes, if cargo sends us underscores we'll report underscores.

**Comment by weihanglo** [comment]
`cargo metadata` is a built-in command   in Cargo. `cargo_metadata` is a library parsing that JSON output. If you have questions about `cargo metadata` please file issues against rust-lang/cargo with detailed use cases and reproduction.

**Comment by adpaco-aws** [comment]
Understood, thank you for your comments! I'll close this issue and open another one in `rustlang/cargo` once I've collected more details about our use-case 😄
