### ISSUE TITLE
Capture stdout to return more informative error messages

### ISSUE THREAD

**Issue by nhynes** [oli-obk/cargo_metadata#29]
@ref https://github.com/rust-lang-nursery/rustfmt/issues/2379

The basic idea is that [simply reporting failure](https://github.com/oli-obk/cargo_metadata/blob/master/src/lib.rs#L250) rather than an error message creates confusion when this crate is used downstream. One proposal is to capture stderr and include that as the returned `err.description`.

**Comment by oli-obk** [comment]
Fixed in 0.5.0

**Comment by nhynes** [comment]
🥇 rockin' maintainer award :)
