### ISSUE TITLE
"missing field workspace_root" error in 0.5.3 (Not present in 0.4)

### ISSUE THREAD

**Issue by George3d6** [oli-obk/cargo_metadata#34]
The following invocation: 

`    let deps = &cargo_metadata::metadata_deps(Some(Path::new("Cargo.toml")), true).unwrap();`

throws the error:

`"missing field `workspace_root`" `

I assume this may be related to the field "workspace_root" in the Metadata structure being a `String` rather than a `Option<String>` ? 

The Cargo.toml itself is valid.

**Comment by oli-obk** [comment]
I fixed this in 0.5.4 (I hope, please try it out) In the next non patch release I'll turn it into an `Option`

**Comment by Deedasmi** [comment]
0.5.4 appears to fix it! Thanks!
