### ISSUE TITLE
Capture original package id in WorkspaceMember

### ISSUE THREAD

**Issue by CodeSandwich** [oli-obk/cargo_metadata#35]
The metadata JSON has full package ids on `workspace_members` list. During creation of `WorkspaceMember` it is parsed into 3 fields and the original value is dropped. It would be nice to have the original id there too. It would make finding workspace packages on `packages` list easier.

**Comment by oli-obk** [comment]
Will be fixed in the 0.6 release

The current fields have become methods on the object and the original value is now the only field (called `raw`)
