### ISSUE TITLE
[Feature Request] Support `cargo build --build-plan`

### ISSUE THREAD

**Issue by konstin** [oli-obk/cargo_metadata#46]
`cargo build --build-plan -Z unstable-options` emits a build plan a nested json. It would be great if cargo_metadata could deserialize the build plan into structs. It should be possible to mostly copy the definitions from https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/build_plan.rs.

**Comment by est31** [comment]
cargo-udeps would greatly benefit from this. Right now we use a custom executor trait impl but a build plan would do the job as well I think and reduce the dependencies of cargo-udeps. It would be great to have abilities for executing the build plan as well, with optional caching and parallelism support.

**Comment by est31** [comment]
The build plan option is being removed so I guess this issue should be closed: https://github.com/rust-lang/cargo/pull/7902
