### ISSUE TITLE
rust-semverver

### ISSUE THREAD

**Issue by gnzlbg** [oli-obk/cargo_metadata#60]
I'd like to use `cargo-metadata` for `rust-semverver` instead of relying on cargo. 

I need to be able to:

* construct a `(package, workspace)` pair for the local directory 
* construct a `(package, workspace)` pair by fetching a package of a specific name and version (downloading the package, etc.)
* compile a `(package, workspace)` pair, e.g., producing an rlib, with some RUSTFLAGS (equivalent operation to `cargo::ops::compile(&workspace, &opts)` ), and obtain the path to the rlib of the package as well as the path to the deps output directory

Which of these operations would belong in `cargo_metadata` and which ones would not ? What should I do about the operations that do not belong here ? (e.g. where should I put these?)

**Comment by oli-obk** [comment]
Uh... `cargo-metadata` only shells out to `cargo metadata` and parses the json dump. I'm not sure what you mean by "constructing a ... pair"

**Comment by gnzlbg** [comment]
>  I'm not sure what you mean by "constructing a ... pair"

I meant constructing a cargo [`Package`](https://docs.rs/cargo/0.32.0/cargo/core/package/struct.Package.html) and [`Workspace`](https://docs.rs/cargo/0.32.0/cargo/core/struct.Workspace.html) types (or equivalent `cargo_metadata` ones).

**Comment by oli-obk** [comment]
yea, the first part is exactly what this crate already does.

The other two seem out of scope, but you should be able to implement the second one trivially on top of this crate.

The third one is definitely out of scope and would require quite some additional work

**Comment by gnzlbg** [comment]
I might be able to call cargo for the third one, but then I will need to somehow interface the types of this crate with the ones from cargo.

**Comment by jyn514** [comment]
> I might be able to call cargo for the third one, but then I will need to somehow interface the types of this crate with the ones from cargo.

You can do that with [`Message::parse_stream`](https://docs.rs/cargo_metadata/0.13.1/cargo_metadata/enum.Message.html#method.parse_stream) (see the third example on https://docs.rs/cargo_metadata/0.13.1/cargo_metadata/#examples).

**Comment by morr0ne** [comment]
Should this issue be closed? I feel like it has already been answered 2.5 years ago.
