### ISSUE TITLE
Documentation uses deprecated trim_left_matches

### ISSUE THREAD

**Issue by imp** [oli-obk/cargo_metadata#65]
`trim_left_matches` has been (or going to be soon?) deprecated in favor of `trim_start_matches`.
Perhaps the documentation should be updated to use the latter?

**Comment by imp** [comment]
Apparently, this will also necessitate the update of the oldest supported compiler version to 1.30.0

**Comment by oli-obk** [comment]
Let's do that when it actually becomes deprecated so we have at least a few stable compilers that already support it.
