### ISSUE TITLE
Error on crates depending on binary crates

### ISSUE THREAD

**Issue by flodiebold** [oli-obk/cargo_metadata#66]
If I have a workspace with a binary crate and another crate declaring a dependency on that binary crate (notwithstanding whether that makes sense), `cargo metadata` outputs a depedency with name `null`. Since `cargo-metadata` expects dependencies to always have a name, it fails to deserialize that metadata.

Here's a minimal reproduction: https://github.com/flodiebold/cargo-metadata-bug

**Comment by oli-obk** [comment]
Huh. Isn't that rather a bug in `cargo metadata`? Shouldn't it be emitting the binary crate's name?

**Comment by flodiebold** [comment]
I'm not sure. I guess since you can't really use the binary crate from the code, it puts null there? I haven't investigated it further so far...

**Comment by ehuss** [comment]
I mentioned this [here](https://github.com/oli-obk/cargo_metadata/pull/61#issuecomment-453240969), and have a PR to change it on the Cargo side (https://github.com/rust-lang/cargo/pull/6534).  However, there is some minor disagreement on how it should be fixed.

**Comment by ehuss** [comment]
This is now fixed on the latest nightly (via rust-lang/cargo#6534), so I think this can be closed.
