### ISSUE TITLE
Consider switching to a error type which is `Sync`

### ISSUE THREAD

**Issue by rustonaut** [oli-obk/cargo_metadata#67]
Consider switching to a error type which is `Sync` (so that it can be turned into a `Failure` error).

`Fail` requires `Send`+`Sync`+`'static` but error chain errors are not `Sync` (due to the way they handle backtraces if I remember correctly).

**Comment by rustonaut** [comment]
Through there are other reasons why having a error being `Sync` is nice, too. They are just rare.

**Comment by oli-obk** [comment]
Hmm... Any tips how to do that? I have never looked into error handling much

**Comment by rustonaut** [comment]
A simple (but braking) change would be to use `failure`:

```rust
use std::{
    io,
    str::Utf8Error,
    string::FromUtf8Error
};

/// Custom result type for `cargo_metadata::Error`
pub type Result<T> = ::std::result::Result<T, Error>;

/// Error returned when executing/parsing `cargo metadata` fails.
#[derive(Debug, Fail)]
pub enum Error {

    /// Error during execution of `cargo metadata`
    #[fail(display = "error during execution of `cargo metadata`: {}", stderr)]
    CargoMetadata {
        /// stderr returned by the `cargo metadata` command
        stderr: String
    },

    /// IO Error during execution of `cargo metadata`
    #[fail(display = "{}", 0)]
    Io(io::Error),

    /// Output of `cargo metadata` was not valid utf8
    #[fail(display = "{}", 0)]
    Utf8(Utf8Error),

    /// Error output of `cargo metadata` was not valid utf8
    #[fail(display = "{}", 0)]
    ErrUtf8(FromUtf8Error),

    /// Deserialization error (structure of json did not match expected structure)
    #[fail(display = "{}", 0)]
    Json(::serde_json::Error)
}

impl From<io::Error> for Error {
    fn from(v: io::Error) -> Self {
        Error::Io(v)
    }
}

impl From<Utf8Error> for Error {
    fn from(v: Utf8Error) -> Self {
        Error::Utf8(v)
    }
}

impl From<FromUtf8Error> for Error {
    fn from(v: FromUtf8Error) -> Self {
        Error::ErrUtf8(v)
    }
}

impl From<::serde_json::Error> for Error {
    fn from(v: ::serde_json::Error) -> Self {
        Error::Json(v)
    }
}
```

(Or use some crate to do the derives for you).

Pro:
1. is `Send` + `Sync` + `'static` 
2. simple "auto" display generation
3. simple to use
4. implements `Failure` (so people can e.g. directly turn it into a `failure::Error`, which is more or less a error trait object, i.e. a better version of `Box<::std::error::Error`)

Cons:
1. doesn't implement `std::error::Error` (as rust doesn't have yet the necessary specialization mechanism)
   - but there is a `.compat()` method which returns `Compat<Self>` which implements `StdError`
2. does not have it's own backtrace
   - we can use `Context<>` in the enum variants to add in a backtrace (e.g. `Io(Context<io::Error>)`)
   - or we have something more like error chain which is roughly a `Context<Error>` of the above error
   - also if a api consumer turns the error into a `failur::Error` it get's a backtrace to the api call which failed (through not into the place inside of the api call where the failure  was triggered)

Given that there aren't much error cases a option would be to just have a error like above
but then to hand implement `std::error::Error` (with `source()`, potentially ignoring the soft-deprecated `description()` method). Compared to the code above you would need to hand implement
`Display` and also would not have a `Backtrace` in the error but except that have the same
benefits.  `Fail` is implemented for anything implementing `StdError` so it's easy  for a api consumer to convert the error to one with `Backtrace` (e.g. using `?` and a `failure::Error` return type).

---
Honestly I'm currently not really satisfied with any of the error approaches in rust:

1. error_chain: not `Sync` documents to put only lightweight data into error kind, but in the
   end all context information is put into it.
2. failur: potentially more code to write (`From` methods etc.). `Context` is less a context and more a node in a error chain, i.e. isn't named appropriately (and wasn't advertised appropriately either, at last the last time I read there non api-docs)
3. std error: description is pointless, `cause` isn't static, which was partially fixed by `source` but is a mess as `Error` (and as such the cause/source) doesn't need to be static so returning `None` on `source()` doesn't mean there is no source. There might be a non-`'static` source ....
4. all of them: aren't really good at handling some additional context information (metadata) and errors which capture references to their source

**Comment by rustonaut** [comment]
I can make a pull-request if you decide for any of the methods above .

**Comment by oli-obk** [comment]
I do like the simplicity of your suggested `failure` errors. Being a breaking change and thus requiring a major version bump is kind of a bummer, but I guess users can live with it.
