### ISSUE TITLE
Failure to parse with `CARGO_PROFILE` set 

### ISSUE THREAD

**Issue by sanmai-NL** [oli-obk/cargo_metadata#76]
`cargo metadata` output cannot be parsed by this crate when the environment variable `CARGO_PROFILE` is set. See https://github.com/rust-lang/cargo/blob/2ed31b02a80ad89e40864ecbed30f02992566e3d/ARCHITECTURE.md#logging. I get an error message "invalid type: integer `0`, expected struct Metadata at line 1 column 11" with `cargo_metadata` version 0.7.3.

**Comment by oli-obk** [comment]
I don't think we can solve this nicely. The output of `cargo metadata` is suddenly preceded by

```
          0ms - updating: /home/oliver/Projects/rust/cargo_metadata
         55ms - resolving
              0ms - updating: registry `https://github.com/rust-lang/crates.io-index`
          0ms - resolving w/ overrides...
          1ms - resolving
```

I'll just filter out all lines that don't start with `{` for now, but this should probably be solved by cargo
