### ISSUE TITLE
Add ability to get data for build scripts.

### ISSUE THREAD

**Issue by icefoxen** [oli-obk/cargo_metadata#77]
Not quite sure where to find it yet, but it should show up as something like this in the target list:

```
{
    "kind": [
        "custom-build"
    ],
    "crate_types": [
        "bin"
    ],
    "name": "build-script-build",
    "src_path": "/Users/eric/Proj/rust/cargo/scratch/b/build.rs",
    "edition": "2018"
}
```

I THINK right now it just shows up as `DependencyKind::Unknown`, but adding support for it should hopefully not be *too* painful.  I'll see what I can come up with.  All I actually want so far is whether a build script is present and what the path to it is, though someday I probably want to get the dev-dependencies of it too.

**Comment by ehuss** [comment]
The build script is a target in `Package::targets` with a kind of "custom-build".

```rust
let metadata = cargo_metadata::MetadataCommand::new()
    .no_deps()
    .exec()
    .unwrap();
let targets: Vec<_> = metadata
    .packages
    .iter()
    .flat_map(|package| &package.targets)
    .filter(|target| target.kind.contains(&String::from("custom-build")))
    .collect();
println!("{:#?}", targets);
```

**Comment by icefoxen** [comment]
Awesome, that looks like it does the trick.  Thanks!
