### ISSUE TITLE
Cannot pass both no-default-features and features

### ISSUE THREAD

**Issue by epage** [oli-obk/cargo_metadata#79]
All, NoDefault, and Features are in an `enum`, making them mutually exclusive.  This would be fine except that they are then stored in `MetadataCommand` as a `Option<CargoOpt>`.  This prevents doing `--no-default-features --features "one-of-the-default"`.

**Comment by epage** [comment]
I was also surprised that `Features` owns a `Vec<String>`.  Before looking at the code, I assumed `MetadataCommand` owned a `std::process::Command` and that `MetadataCommand` just forwarded calls to it.

**Comment by oli-obk** [comment]
> I assumed MetadataCommand owned a std::process::Command and that MetadataCommand just forwarded calls to it.

That... seems very reasonable. Not sure why I wrote the code the way it is. You should be able to address this without touching the user-exposed API.

**Comment by epage** [comment]
> That... seems very reasonable. Not sure why I wrote the code the way it is. You should be able to address this without touching the user-exposed API.

iirc you'd lose the ability to `Clone`.

**Comment by epage** [comment]
If we want to aim for consistently wrapping `process::Command`, here is [escargot's feature functions](https://docs.rs/escargot/0.4.0/escargot/struct.CargoBuild.html#method.all_features).

**Comment by ricobbe** [comment]
Looks like #118 addresses this problem, which is great.  Do you have an estimate of when this fix will be published to crates.io?

**Comment by oli-obk** [comment]
oops, I published a new version with this, thanks for the ping
