### ISSUE TITLE
package.readme is String rather than PathBuf

### ISSUE THREAD

**Issue by imp** [oli-obk/cargo_metadata#86]
While tinkering with rust-lang/rust-clippy#4517 I noticed that `package.readme` is defined as `Option<String>`. However, [documentation](https://doc.rust-lang.org/cargo/reference/manifest.html) claims it is actually a filename, so `PathBuf` could be more appropriate in this case (just like `package.license-file`).

**Comment by imp** [comment]
In any case it may be more appopriate to treat both `license-file` and `readme` same way: either both `String` or both `PathBuf`.

**Comment by oli-obk** [comment]
Both shuld be `PathBuf` indeed.
