### ISSUE TITLE
fails to parse Cargo.toml if regex used in paths to workspace members.

### ISSUE THREAD

**Issue by matthiaskrgr** [oli-obk/cargo_metadata#90]
Cargo.toml:
````toml
[workspace]
members = [ "crates/*", "xtask/" ]

[profile.dev]
debug = 1 # only line info

[profile.release]
incremental = true
debug = 1 # only line info

[patch.'crates-io']
````

The `Cargo.toml` is from rust-analyzer:
https://github.com/rust-analyzer/rust-analyzer/blob/5376c769f0cb6076c4862e728af042bb563a5051/Cargo.toml

cargo_metadata seems to fail to resolve the regex inside `members = [ "crates/*", "xtask/" ]`:
``Err(CargoMetadata { stderr: "error: failed to read `/tmp/ttest/crates/*/Cargo.toml`\n\nCaused by:\n  No such file or directory (os error 2)\n" })``
Cargo does not seem to have a problem doing so.

cargo-metadata 0.8.2

**Comment by oli-obk** [comment]
O_o You scared me for a moment. Those aren't regexes but simple glob paths. I guess we can start treating them as such and use all workspace elements

**Comment by ehuss** [comment]
That error seems to be coming from cargo.  I can't reproduce it, though.  Can you give exact steps to repro it?

**Comment by matthiaskrgr** [comment]
Oh I see, the problem was that I was running with `.features(CargoOpt::AllFeatures)` on a crate with multiple workspaces which immediately errored/paniced in my case :sweat_smile:
