### ISSUE TITLE
waits for ~/.cargo in unresonable situations

### ISSUE THREAD

**Issue by matthiaskrgr** [oli-obk/cargo_metadata#99]
in `cargo-cache`, I use `cargo-metadata` to get the target-dir of a project, roughtly like this:
````rust
  let target_dir = MetadataCommand::new()
        .manifest_path(&manifest)
        .exec().unwrap().target_directory
````
and it seems that cargo-metadata stalls while doing that if I write to the `$CARGO_HOME` (for example by doing a `cargo fetch`) at the same time.
This seem unreasonable since the dep source cache and a local projects target dir don't need to be blocking each other I think?

**Comment by ehuss** [comment]
Have you tried with `.no_deps()`?  With deps, it needs to run the resolver which requires access the the registry and its caches.

**Comment by matthiaskrgr** [comment]
Oh, that's perfect thanks!
I never noticed that it would actually fetch deps under the hood, oops!
